/**
 * Generated by tsnapi — public API snapshot of `@zjy040525/ccrc-crypto` */
// Classes
export declare class Crypto {
  key: string;
  iv: string;
  constructor(key: string, iv?: string);
  private getIvBuffer;
  private importKey;
  encrypt(word: string): Promise<string>;
  decrypt(word: string): Promise<string>;
}